#!/bin/bash

make test

echo "HalfSteps SingleRow"
./cuda_half | grep -e SUCCESS -e FAILURE
echo

echo "NSteps SingleRow"
./cuda_n | grep -e SUCCESS -e FAILURE
echo

echo "Sequential Quadratic"
./seq_quad | grep -e SUCCESS -e FAILURE
echo

echo "Sequential Linear"
./seq_lin | grep -e SUCCESS -e FAILURE
echo
